-- from the terminal run:
-- psql < seed_reward_rates.sql


-- \c capstone_one

DROP TABLE IF EXISTS reward_rates;

CREATE TABLE reward_rates
(
  id SERIAL PRIMARY KEY,
  points FLOAT,
  description TEXT
);

  INSERT INTO reward_rates
    (points, description)
  VALUES                                                                                                                                                                                                                                            
(2, 'Earn 2 points per $1 spent on Southwest Airlines purchases.'),
(3, '3 miles for every qualifying dollar in purchases of Alaska Airlines tickets, Vacation packages and Cargo purchases.'),
(3, 'Selectable Category'),
(2, 'Earn 2 ThankYou® Points per $1 spent on dining out and entertainment.'),
(5, 'Earn 5% cash back on all purchases at Target stores and online at Target.com.'),
(2, '2% cash back on every purchase.'),
(1, 'No cash back rewards.'),
(1, 'Earn 1% cash back on all other purchases'),
(2, 'Earn 2 MileagePlus miles for each $1 spent at restaurants, gas stations, and office supply stores.'),
(1, '1% cash back on all other purchases.'),
(5, 'Unlimited 5% back on gas purchases & sporting goods purchases.'),
(2, 'Earn 2X miles  for every one dollar spent on eligible American Airlines purchases.'),
(1, '1% cash back on purchases everywhere, every time.'),
(4, '4% cash back on gas station purchases (in-store and at the pump) for the first $8,000 in combined purchases'),
(3, '3% back in rewards at restaurants'),
(2, 'Earn 2 miles per $1 spent at restaurants and hotels'),
(2, '2 Miles per dollar spent on purchases at U.S. supermarkets.'),
(1, 'One FlexPoint for every $1 of eligible Net Purchases charged to your Card'),
(1, 'Earn 1 Point for every $1 you spend on other purchases. You also earn points with this AT&T credit card for pumping gas, buying groceries or making any other purchase with your card.'),
(2, 'Earn 2 miles per $1 spent at restaurants and on hotel accommodations when purchased directly with the hotel'),
(1, '1% Shell rebates on other qualifying purchases'),
(2, 'Earn 2x miles at U.S. Supermarkets'),
(2, 'Earn 2 Points for every $1 you spend on purchases made online at eligible retail and travel websites.'),
(1, 'Earn 1 FlexPoint for every dollar of net purchases on everything else.'),
(3, '2% at grocery stores and 3% on gas for the first $1,500 in combined grocery store and gas purchases each quarter.'),
(0, 'When you pay your monthly cell phone bill with your eligible Wells Fargo consumer credit card, you can receive up to $600 of protection (subject to $25 deductible) against covered damage or theft.'),
(1, 'Earn 1 ThankYou® Point for every $1 you spend.'),
(5, 'Earn 5 points on airfare purchases.'),
(5, '5 points per dollar spent on internet'),
(2, 'Earn 2 miles for every $1 spent on eligible American Airlines purchases'),
(3, '3% cash back on dining purchases at restaurants, including fast food for the first $8,000 in combined purchases'),
(2, '2% back for online purchases. Includes Uber, online shopping, video and music streaming services.'),
(1, 'Earn 1 point for every $1 in Card purchases everywhere else'),
(3, '3X points for every $1 spent at 7,000+ participating Marriott BonvoyTM hotels'),
(2, '2% back Walmart stores, Walmart & Murphy USA Fuel Stations, Restaurants & travel'),
(3, '3x Membership Rewards points on travel including flights, hotels, transit, taxis, tours, and ridesharing services'),
(1, 'Unlimited 1% Cash Back on all other purchases'),
(1, 'Earn 1% rebates on all other eligible purchases.'),
(0, 'No rewards.'),
(3, 'Earn 3 ThankYou points for every $1 spent on purchases made online at retail and travel websites.'),
(1, '1% back in rewards on all other purchases  made with your IKEA Visa credit card'),
(1, 'Earn 1 LifeMile per $1 spent on all other purchases'),
(3, '3X points at restaurants'),
(2, 'Earn 2X AAdvantage® miles  for every one dollar spent on eligible American Airlines purchases'),
(2, '2% Back at U.S. restaurants, U.S. gas stations, and on wireless telephone services purchased directly from U.S. service providers'),
(5, 'Earn 5 percent on fuel purchases (on first $6,000 per year).'),
(0, 'No other cash rewards.'),
(5, 'Earn 5% cash back at gas stations.'),
(1.5, '1.5% cash back on all purchases'),
(1, '1x points on all purchases.'),
(1, 'Earn 1 point for every $1 spent on all purchases'),
(1, 'Earn 1 Star per $4 on purchases everywhere else'),
(5, 'Earn 5 HHonors Bonus Points per $1 spent on airline and car rental purchases.'),
(2, '2 points at participating Cenex gas stations and convenience stores'),
(3, 'Earn 3X points on your mobile phone bill payments'),
(1, 'Earn 1X points per $1 spent on all other Mastercard purchases.'),
(2, '2% Cash Back at select U.S. department stores'),
(3, '3% Cash Back at U.S. gas stations.'),
(2, '2x points for purchases at MINI dealerships as well as for motoring-related expenses like gas, tolls and car washes.'),
(2, 'Earn 2 FlexPoints on Gas and Grocery net purchases.'),
(3, 'Earn 3 percent on dining and travel.'),
(3, 'Earn 3 points per $1 spent in eligible net purchases everywhere else.'),
(4, '4x Points on all travel purchases for PenFed Honors Advantage Members.'),
(1, 'Earn 1 Expedia+ bonus point per $1 spent on other purchases.'),
(3, '3% back in rewards on gas purchases'),
(1, 'Earn 1 point per dollar spent everywhere else.'),
(2, '2 points per dollar spent on office supplies'),
(2, 'Double Miles on LAN ticket purchases'),
(2, '2X points at restaurants and office supply stores'),
(5, 'Earn 5 points per $1 spent in eligible net purchases everywhere else.'),
(1, 'Earn 1% cash back everywhere else.'),
(2, 'Earn 2x miles  on gas, dining and grocery store purchases.'),
(2, '2 points per $1 spent on Southwest Airlines® and Rapid Rewards® Hotel and Car Rental Partner purchases'),
(1, 'Earn 1 point per $1 on all other purchases'),
(3, '3 points per eligible net $1 on the Kroger Family of Companies Own Brand Products.'),
(1, 'Earn 1 Star per $2 you spend at grocery stores, on local transit and commuting, and on internet, cable, and phone services'),
(2, 'Earn unlimited 2X miles on every purchase for your business.'),
(2, 'Earn 2 AAdvantage® miles for every $1 you spend on eligible American Airlines and US Airways purchases'),
(1, '1 point per eligible net $1 spent anywhere1 Mastercard is accepted.'),
(2, '2x points at US Gas Stations'),
(1, '1% other purchases'),
(1.5, '1.5 points per $1 on all other purchases.'),
(10, 'Earn 10 points per $1 spent at participating Carlson Rezidor hotels worldwide.'),
(1, 'Earn 4X Membership Rewards® points on the 2 categories where your business spent the most each billing cycle, including U.S. purchases at gas stations. Earn 1x on other purchases.'),
(1, '5 points for every $1 spent in-store and online at Gap, Old Navy, Banana Republic, and Athleta; 1 point for every $1 spent everywhere else'),
(6, '3x points for every $1 spent at over 7,000 participating Marriott Bonvoy hotels worldwide.'),
(1, 'Earn 1 MileagePlus mile for each $1 everywhere else.'),
(2, 'Earn 2% cash back on all eligible purchases up to $50,000 per calendar year, then 1% cash back applies after that.'),
(5, 'Earn 5% cash back on up to $3,000 in gas and military base purchases every year.'),
(1, 'Earn unlimited 1 Point Per $1 spent on all other purchases. Points do not expire as long as your account is open.'),
(2, 'Earn 2X points for every $1 spent on purchases in these categories now through 6/30/2020: CareCredit Network, Health & Wellness, Grocery Stores, Pet Stores'),
(2, 'Earn 2% rebates on all eligible travel and dining purchases.'),
(1, '1X on All Other Purchases.'),
(3, '3% cash back on gas.'),
(2, '2X cash back rewards on gas, groceries and utilities.'),
(5, 'Earn 5 points per $1 spent on every participating hotel stay'),
(3, 'Earn 3 TD Points for every $1 you spend on Purchases made using your Card'),
(1, 'Earn 1 mile per $1 on all other purchases.'),
(1, 'Earn 1 for every $1 spent on all other purchases.'),
(1, '1% back in Uber Cash on all other purchases.'),
(2, 'Earn 2 points at Southwest Hotel and Car Rental Partners.'),
(1, '1 mile for every other purchase.'),
(6, '6% Cash Back on select U.S. streaming subscriptions.'),
(5, '5 points per dollar spent on office supplies'),
(2, 'Earn 2% in reward dollars on card purchases at gas stations, grocery stores, restaurants, and most Disney locations.'),
(5, 'Get 5X Membership Rewards® points on flights and prepaid hotels on amextravel.com'),
(2, 'Earn two reward points for every dollar spent'),
(3, '3x points per $1 spent on eligible airfare, hotel, and dining purchases up to $2,500 in combined net spend each calendar quarter.'),
(3, '3 Miles on every dollar spent on eligible purchases made directly with Delta.'),
(2, 'Earn 2X points per $1 on restaurants.'),
(2, '2X points on dining at restaurants.'),
(2, 'Earn 2x points on recurring bills, groceries, dining and more with no limits.'),
(2, '2% value for airfare redemptions'),
(3, '3% cash back on dining, gas and groceries'),
(2, 'Earn 2% cash back on the first $25,000 spent in combined purchases at gas stations and restaurants each account anniversary year'),
(2, '2% Back in Rewards for every $1 spent on Gas & Groceries using your Bed Bath & Beyond® Mastercard Credit Card'),
(2, '2 points for every $1 spent at restaurants, on airline tickets purchased directly from the airline and at car rental agencies.'),
(5, 'Earn 5% back at Amazon and Whole Foods from 7/1/2020 - 9/30/2020 on up to $1,500 in purchases.'),
(5, 'Selectable Category'),
(3, 'A true cashback card: 3% cash back in year one & 2.5% cash back after'),
(1.25, '1 mile per dollar spent on all other purchases'),
(1, '1X points on other purchases'),
(2, '2% Back at US restaurants, US gas stations, and on wireless telephone services purchased directly from US service providers.'),
(1.5, 'Earn unlimited 1.5% Cash Back rewards on every purchase made for your business.'),
(2, '2% cash back at restaurants, gas stations, and supermarkets'),
(1, 'Earn 1x points everywhere else.'),
(2, '2% Cash Back: Gas, Restaurants'),
(1, 'Earn 1 point for every $1 you spend on all other purchases with your card.'),
(1, 'Use your card everywhere else and earn 1 point per $1 on all of your purchases'),
(5, 'Earn 5x points on qualifying utilities, cell, cable, Amazon Prime, and streaming subscription services up to $1,500 in combined purchases. Must have a registered account at ABOCRewards.com. Valid 1/1/2020 - 3/31/2020.'),
(0, 'No spending bonus.'),
(2, 'Earn 2 Rewards Points for every $1 spent on groceries, gas, electronics, medical, household goods and telecommunications'),
(2, 'Earn 2% back in reward dollars on grocery store purchases'),
(1.25, 'Earn unlimited 1.25 miles on every purchase, every day.'),
(2, 'Earn 2X points per $1 spent on gas, restaurant, and groceries.'),
(1, 'Earn 1X Mile on all other eligible purchases.'),
(5, 'Earn 5X miles on hotel and rental car bookings through Capital One Travel℠ using a Spark Miles Select card'),
(1, 'Earn 1% cashback on all purchases'),
(2, 'EARN 2X MARRIOTT BONVOY POINTS on all other eligible purchases.'),
(1, 'Earn 1 Thank You point for every $1 spent on other purchases.'),
(2, 'Earn 2% cash back on up to $3,000 in supermarket purchases per year.'),
(1, '1x points on other purchases'),
(2, 'Earn 2 points for every $1 you spend on Southwest Airlines® purchases.'),
(0, '$10 Reward With Every 500 Points Earned'),
(3, '3x points at US Supermarkets'),
(1, 'Earn 1% Cash Back wherever Visa is accepted.'),
(1.5, 'Earn 1.5% cash back on every purchase'),
(2, '2 points for each dollar at restaurants and grocery stores'),
(1, '1% cash back on up to $3,000 in debit card purchases each month.'),
(1, '1% Cash Back: All Other Purchases'),
(2, '2 points per dollar spent on phone'),
(5, 'Earn up to 5 points per dollar spent at gas stations.'),
(2, 'Earn 2 miles per $1 on FlyFrontier.com purchases'),
(3, 'Earn 3% cash back on gas stations, restaurants, office supply stores & home improvement stores (up to $2,000 per month).'),
(2, '2% Total Cash Back for PenFed Honors Advantage Members.'),
(2, 'DOUBLE POINTS When Redeemed for Airfare'),
(3, 'Earn 3 points for every $1 on dining, car rentals and airline purchases'),
(0, 'Earn 5% cash back at the register at Target stores and target.com; no other rewards.'),
(2, '2% Cash Back on Gas & Groceries.'),
(6, 'Earn 6 points per $1 spent at participating Carlson Rezidor hotels worldwide.'),
(8, 'Earn up to 8 TrueBlue points for each dollar spent on JetBlue purchases.'),
(5, 'Earn 5 percent on fuel purchases on up to $5,000 per year.'),
(3, 'Earn 3% cash rewards on cellular, gas and purchases made at office supply stores'),
(3, '3X points on gas and transit'),
(2, 'Earn 2 points for every $1 spent on eligible transit & gas purchases in Canada and eligible travel purchases'),
(1.5, 'Earn 1.5 miles per $1 on every purchase.'),
(3, '3 Miles per dollar spent on purchases made directly with hotels.'),
(4, '4x points per $1 spent on gas, restaurants, shipping and for internet, cable and phone service purchases'),
(7, 'EARN 7X HILTON HONORS BONUS POINTS for each dollar of eligible purchases charged on your Card directly with a hotel or resort within the Hilton Portfolio.'),
(3, '3 Avios per dollar spent with British Airways, Aer Lingus, Iberia, and Level.'),
(1, 'Earn 1 Rapid Rewards points per $1 spent on all other purchases.'),
(2, '2 points per dollar spent at US gas stations'),
(0, 'Bonus earnings only on Amazon purchases.'),
(2, '2% cash back on your purchases at gas stations and grocery stores.'),
(3, 'Earn 3 ThankYou points for every $1 spent on products & services directly purchased from AT&T.'),
(1, 'Earn 1 Reward Point for every $1 spent on all other purchases'),
(10, '10 points per $1 spent in eligible net purchases at participating Carlson Rezidor hotels worldwide.'),
(2, 'Earn 2 miles per dollar spent at United.'),
(1.5, 'Earn unlimited 1.5 points for every $1 you spend on all purchases everywhere.'),
(12, 'EARN 12X HILTON HONORS BONUS POINTS for each dollar of eligible purchases charged on your Card directly with a hotel or resort within the Hilton Portfolio.'),
(1, 'Earn 1 AAdvantage® mile per dollar spent on all other purchases'),
(2, '2% back in rewards on dining and grocery purchases'),
(1, 'Earn 1 point per dollar spent on purchases everywhere.'),
(1, 'Earn Rewards! on all purchases with a 1 point for $1 spent program'),
(3, 'Earn 3 points for every $1 you spend on Southwest Airlines® purchases.'),
(2, '2X at Supermarkets & Gas Stations for the first $6,000 per year and 1 point per $1 spent thereafter.'),
(0, 'No cash back rewards.'),
(6, '6X points on JetBlue purchases'),
(1, 'Earn 1 Point per $1 spent on all other purchases.'),
(2, 'Earn 2 points per $1 spent on purchases at gas stations, grocery stores, and restaurants.'),
(5, '5% off your purchase when you use your Academy Sports + Outdoors Credit Card in stores and Academy.com'),
(1, '1% cash back on eligible purchases.'),
(6, '6X Points Per dollar on select business purchases on wireless telephone services purchases directly from U.S. service providers'),
(2, 'Earn 2 points and 2 tier credits per $1 spent on gas and supermarkets'),
(1, 'Earn 1 mile for every $1 spent on other purchases'),
(1.25, 'Earn 1.25 points for every dollar spent.'),
(1, '1% cash back for each dollar spent on everyday purchases.'),
(5, 'Earn 5x points on eligible eats & drinks, including restaurants, bars, grocery stores and food delivery in Canada'),
(1, '1% cash back rewards on every purchase, every day'),
(3, 'Earn 3 ThankYou® Points per $1 spent on travel including gas.'),
(1, '1 point for each dollar on everything else'),
(0, 'No cash rewards.'),
(1.25, 'Accelerate your earn rate to 1.25 Aeroplan Miles for every additional $1 in Card purchases over $10,000 annually'),
(3, '3 points per $1 on qualifying air and hotel purchases.'),
(2, 'Earn 2 Rapid Rewards points per $1 spent on Southwest Airlines purchases.'),
(2, '2 points per dollar spent on car rentals'),
(5, '5% back with an eligible Amazon Prime membership'),
(1.5, '1.5% cash back on every dollar you spend everywhere! Cash Rewards can be deposited right into your checking or saving account.'),
(1, 'Earn one Membership Rewards® point for every eligible dollar you spend.'),
(2, 'Earn 2x Aeroplan Miles per $1 spent on Air Canada net purchases'),
(6, 'Earn 6 Hilton HHonors Bonus Points for each dollar of eligible purchases on your Card at restaurants, gas stations and supermarkets.'),
(1, '1% instant cashback from up to 6 premium retailers.'),
(1.5, 'Unlimited 1.5% Cash Back'),
(2, 'Earn 2 miles for each $1 spent on tickets purchased from United'),
(3, 'Earn 3% cash-rebate on gas, grocery, and restaurant purchases.'),
(2, 'Earn 2 AAdvantage® miles for every $1 spent on eligible American Airlines purchases.'),
(1, '1x Delta SkyMiles for each dollar spent on other eligible purchases.'),
(2, 'Earn 2 points for every $1 spent on airline tickets purchased directly with the airline, and at car rental agencies & restaurants.'),
(5, 'Earn 5% back at Home Improvement Store and Popular Streaming Services from 7/1/2020 - 9/30/2020. Your total annual (calendar year) cash back is limited to $300 and includes additional cash back earned in connection with this offer.'),
(2, '2% cash back on grocery store purchases for the first $8,000 in combined purchases'),
(2, 'Earn 2% cash back automatically on up to $1,000 in combined purchases at restaurants and gas stations every quarter-no sign-ups needed.'),
(6, 'EARN 6X HILTON HONORS BONUS POINTS for each dollar of eligible purchases on your Card at U.S. restaurants, at U.S. supermarkets, and at U.S. gas stations.'),
(3, 'Earn unlimited 1.5% cash rewards on all purchases. (3% the first year up to $10k in spend).'),
(6, '6 points per dollar on Jetblue purchases'),
(2, 'Earn 2 points per $1 spent on other qualifying travel.'),
(1, 'Earn 1 point for every $1 spent on all other purchases'),
(3, '3X Points on new travel purchases – including airline, hotels, and car rentals'),
(2, 'Earn 2 LifeMiles per $1 spent at gas stations and grocery stores'),
(2, 'Earn 2X Miles per dollar at restaurants, now worldwide.'),
(4, 'Earn 4 Expedia+ bonus points per $1 spent on eligible Expedia purchases including flights, hotels, activities and vacation packages.'),
(1, 'The entry-level Zerocard, Quartz earns 1.0% cash back, still a game-changing rewards rate for a product that works with a Debit-style Experience.'),
(1, '1% cash back on all purchases'),
(1.5, '1.5% cash back on purchases.'),
(1, '1 point per dollar spent on all other purchases'),
(0, 'No other rewards.'),
(5, '5% Cash Back on online shopping, travel, and restaurants'),
(2, '2% cash back at grocery stores and wholesale clubs'),
(1, '1X points for each dollar you spend on eligible purchases'),
(2, '2 points per dollar spent on hotels'),
(1.5, 'Get a 1.5% discount when you pay early, with no cap on what you can earn back.'),
(1, '1% unlimited cash back on everything else'),
(2, '2% cash back at U.S. gas stations.'),
(0, 'No bonus rewards.'),
(4, 'Earn 4X Membership Rewards® points at restaurants worldwide'),
(2, '2X points on everything else'),
(2, '2X miles for every dollar spent on eligible American Airlines purchases'),
(1, '1 Avios per dollar spent on all other purchases.'),
(2, 'Earn 2 miles per dollar on every purchase.'),
(6, '6X Points Per dollar on select travel purchases on flights booked directly with airlines or with Amex Travel'),
(3, '3% Back or 60 Day Terms on US purchases at Amazon Business, AWS, Amazon.com, and Whole Foods Market.'),
(3, 'Earn 3 percent on dining and travel on up to $5,000 per year.'),
(2, '2 Avios per dollar spent on hotel accommodations.'),
(3, 'Earn 3 points per $1 on the first $150,000 spent in combined purchases on travel, shipping purchases, Internet, cable and phone services, and on advertising purchases made with social media sites and search engines each account anniversary year.'),
(1, '1% Cash Back on all other purchases'),
(2, '3X points on one category of your choice: Airfare purchased directly from airlines, U.S. purchases for advertising in select media, U.S. purchases at gas stations, U.S. purchases for shipping, U.S. computer hardware, software, and cloud. 2X points on the 4 remaining categories.'),
(1, 'Earn 1 percent on all other purchases.'),
(1.25, 'Earn 1.25% - 1.75% cash back based on amount of spend'),
(10, '10 points per $1 spent everywhere else'),
(1, 'Earn 4X Membership Rewards® points on the 2 categories where your business spent the most each billing cycle, including U.S. purchases at restaurants. Earn 1x on other purchases.'),
(1, 'One LANPASS Mile for every net $1 you spend'),
(3, '3X Points on Travel Worldwide, immediately after earning your $300 annual travel credit.'),
(6, 'Earn 6 HHonors Bonus Points for each $1 spent at a participating hotel within the Hilton HHonors portfolio.'),
(1, '1X points on all other purchases'),
(1.5, '1.5% cash back on all purchases.'),
(3, 'Earn 3x miles  on eligible Hawaiian Airlines purchases.'),
(2, 'Earn 2% at grocery stores and 3% on gas for the first $1,500 in combined grocery store and gas purchases each quarter.'),
(1, '1% MCO rewards on all card spending'),
(5, '5 points per dollar spent on all other purchases'),
(2, 'Earn 1% unlimited cash back on every purchase you make. Earn an additional 1% unlimited cash back as you pay for those purchases, whether you pay in full or over time.'),
(1, 'Earn 4X Membership Rewards® points on the 2 categories where your business spent the most each billing cycle, including airfare purchased directly from airlines. Earn 1x on other purchases.'),
(2, 'Earn 2X AAdvantage® miles  for every one dollar spent at eligible office supply, telecom and car rental merchants'),
(1, 'Earn 1% elsewhere.'),
(7, 'EARN 7X HILTON HONORS BONUS POINTS on eligible purchases on your Card for: • Flights booked directly with airlines or amextravel.com • Car rentals booked directly from select car rental companies • U.S. restaurants.'),
(1, '1x ThankYou® Point  per $1 spent on other purchases.'),
(1, '1 point per $1 spent on all other purchases.'),
(1, 'Earn 1 mile per dollar for purchases you make with your Card.'),
(3, 'Earn 2% at grocery stores and 3% on gas for the first $1,500 in combined grocery store and gas purchases each quarter.'),
(6, '6X Points Per dollar on select business purchases at U.S. gas stations'),
(1.5, 'Earn an unlimited 1.5% cash back automatically deposited into your eligible Schwab account for purchases made with your Card.'),
(15, '15 points total per $1 spent when you stay at any IHG hotel'),
(2, 'Earn 2 points for every $1 you spend on Rapid Rewards® hotel and car rental partner purchases.'),
(3, '3 points for every $1 spent on purchases at all Hyatt properties with your Hyatt credit card.'),
(1, 'Earn 1 point per $1 spent on purchases everywhere else.'),
(3, '3% back on hotel and airfaire. Includes vacation home rentals.'),
(1.6, '1.6% cash back'),
(4, 'Earn 4 Expedia+ bonus points per $1 spent on eligible Expedia purchases including flights, hotels, activities and vacation packages.Air'),
(1.5, '1.5 miles per $1 spent on all other purchases with no limit to the number of miles you can earn'),
(1.5, 'Get unlimited 1.5% cash back on every purchase for your business, with no minimum to redeem.'),
(2, '2x points at US supermarkets, on up to $6,000 per year in purchases (then 1x)'),
(6, 'Save 6¢ on every gallon of gas you pump.'),
(3, 'Earn 3% cash back on all Apple Pay purchases from Nike, Uber, UberEats, Walgreens, Duane Reade, and T-Mobile stores.'),
(1.5, '1.5% cash back on purchases'),
(2, 'Earn 2 Points for every $1 you spend on products and services purchased directly from AT&T. You earn 2X points on AT&T purchases like a new tablet or accessories for your phone.'),
(3, 'EARN 3X HILTON HONORS BONUS POINTS on all other eligible purchases.'),
(2, 'Earn 2 Expedia+ bonus points per $1 spent on purchases for dining out and entertainment, including tickets to concerts, movies and sporting events.'),
(2, 'Earn unlimited 2X miles on every purchase, every day.'),
(1, '1% Back on other purchases'),
(3, 'Earn up to 3 Stars per $1 spent at Starbucks® stores, 1 star per $4 on purchases everywhere else'),
(1, '1 point per dollar spend on everything else'),
(1.25, 'Earn 1.25x the points for every $1 spent on everyday purchases'),
(5, '5 points per dollar spent on phone'),
(2, '2X at Supermarkets & Gas Stations for the first $6,000 per year (and 1 point per $1 spent thereafter)'),
(1, '1 Aeroplan Mile per $1 spent on all other net purchases'),
(1.5, 'Earn 1.5% cash back on all purchases.'),
(0, 'No bonus earnings'),
(3, '3X Points on Dining at Restaurants Worldwide.'),
(1.25, 'Earn 1.25 Aeroplan Miles for every $1 of Card purchases up to $25,000 annually'),
(5, '5X Membership Rewards® points on prepaid hotels booked on amextravel.com'),
(1, 'Earn 1 WorldPoint per dollar spent.'),
(2, '2X Marriott Bonvoy points on all other eligible purchases.'),
(1, 'Earn 1% of your net purchases in State Farm Dollars.'),
(1, '1 Delta SkyMiles on every eligible dollar spent on purchases'),
(1, '1 mile per $1 on all other purchases'),
(2, 'Earn 2 points per $1 spent on purchases everywhere else'),
(3, '3 points for each dollar on Jetblue purchases'),
(6, '6% Cash Back at U.S. supermarkets up to $6,000 per year in purchases (then 1%).'),
(2, '2X points per $1 spent on other travel purchases (from airfare to taxis and trains)'),
(1, 'Earn 1 point per $1 spent on all other purchases.'),
(1, '1 point for all other eligible purchases'),
(2, 'Unlimited 2 points for every $1 spent on travel and dining purchases.'),
(2, 'Earn 2 award miles per $1 on ticket purchases directly from Miles & More integrated airline partners.'),
(1, 'Earn 1% cash back on purchases greater than $3000.'),
(1, 'Earn 1 AAdvantage® mile for every $1 you spend on other purchases.'),
(1, '1 Mile for every eligible dollar you spend on other purchases.'),
(2, '2% in points on eligible purchases at Sears & Kmart'),
(3, '3X points at supermarkets'),
(2, '2% value for cash back and airfare redemptions'),
(5, '5% in points on eligible purchases at gas stations (on the first $10,000 of combined gas, grocery and restaurant purchases per calendar year and 1% thereafter)'),
(5, 'Earn 5% cash back on the first $25,000 spent in combined purchases at office supply stores and on internet, cable and phone services each account anniversary year'),
(2, 'Earn double rewards points on hotels, airlines, and restaurants.'),
(4, '4% cash back on eligible gas, for the first $7,000 per year and then 1% thereafter.'),
(3, '3X points on dining out'),
(2, '2x ThankYou® Points per dollar spent on purchases for dining at restaurants and entertainment.'),
(5, '5% MCO rewards on all card spending'),
(1, 'Earn 1 point on all other purchases'),
(3, 'Earn 3 HHonors Bonus Points for each $1 spent on purchases at supermarkets, drugstores and gas stations.'),
(1, 'Earn 1 point on all other purchases.'),
(2, '2X Miles on every dollar spent on purchases made directly with Delta'),
(2.5, 'You will earn 2.5% Cash Back on all Qualifying Purchases as long as you maintain a Qualifying Direct Deposit each month.'),
(3, '3% Cash Back: Fast Food; 2% Cash Back: Restaurants'),
(1, 'Earn 1 point on everything else.'),
(1, 'Earn 1 Real Life Reward point for every $1 spent on everything else.'),
(3, 'Earn 3% cash back at gas stations and restaurants.'),
(2, 'Earn 2 points per dollar spent on gas, grocery and drug store purchases.'),
(3, 'Earn 3 HHonors Bonus Points per $1 spent on all other eligible purchases.'),
(1, '1X point on everything else'),
(2, 'Earn two miles per $1 spent on tickets purchased from United'),
(1.5, 'Your Miles card earns an unlimited 1.5x Miles on every dollar you spend on purchases.'),
(3, '3% cash back rewards at restaurants.'),
(7, 'Earn 7X Hilton HHonors Bonus Points for each dollar of eligible purchases charged on your Card directly with a participating hotel or resort within the Hilton Portfolio.'),
(1, 'Earn 1% back toward a Sephora Credit Card Rewards when you use your card outside of Sephora'),
(5, 'EARN 5X HILTON HONORS BONUS POINTS for each dollar of eligible purchases on your Card at U.S. restaurants, at U.S. supermarkets, and at U.S. gas stations.'),
(1, 'Earn 1 AAdvantage® mile for every $1 spent on other purchases.'),
(2, 'Double FlexPoints on the category you spend the most on (at gas stations, grocery stores or airlines) and at most cell phone service providers during each billing cycle'),
(3, '3x Membership Rewards points on travel including car rentals'),
(1, '1% Back on all other purchases.'),
(3, '3 Miles per dollar spent on purchases made with Delta.'),
(5, 'Earn 5x points on qualifying airline, cruise, car rental, hotel, travel agency purchases, gas, tolls, and ride share. Must have a registered account at ABOCRewards.com. Valid 7/01/20 – 9/30/20.'),
(6, 'Earn 6x points per $1 spent at 6,700 participating Marriott Bonvoy hotels.'),
(1.5, 'Earn unlimited 1.5X miles on every purchase for your business.'),
(3, 'Earn 3% cash back on all gas station and restaurant purchases.'),
(1, '1% Cash Back on other purchases.'),
(2, 'Earn 2 points for every eligible $1 spent at gas stations, restaurants, office supply stores, and drugstores.'),
(1, 'Earn 1% on purchases over $3000.'),
(2, 'Earn 2% Cash Back at grocery stores'),
(1, 'Earn 3 points per dollar in one category of your choosing each quarter, 1 point per dollar on all other qualifying purchases.'),
(4, 'Earn unlimited 4% cash back on dining and entertainment.'),
(3, '3% Cash Back on Travel & Entertainment on the first $500 in spend each month.'),
(2, 'Earn 2 Rewards Points at qualifying U.S. gas stations and U.S. supermarkets.'),
(2, '2x points for gas and groceries'),
(0, 'No earnings bonus.'),
(2, 'Get 2x the points per purchase'),
(1, '1X Points for each dollar you spend on eligible purchases'),
(1, '1X points per $1 spent on all other purchases'),
(4, '4X Marriott Bonvoy points at U.S. restaurants, at U.S. gas stations, on wireless telephone services purchased directly from U.S. service providers and on U.S. purchases for shipping.'),
(3, 'Earn unlimited 3% cash back on dining and entertainment.'),
(1.25, 'Earn 1 Rewards Point for every $1 you spend in eligible net purchases; receive a 25% bonus by redeeming points for cash back into eligible Ameriprise Financial accounts or for an Ameriprise financial planning certificate — an effective 1.25% cash back per eligible net $1 spent on your card'),
(2, 'Earn 2x points on groceries and restaurants.'),
(3, '3% MCO rewards on all card spending'),
(1, 'Earn 1% Cashback On all other Mastercard purchases.'),
(2, 'Earn 2X back on all purchases made at Priceline.com.'),
(1.5, 'Unlimited 1.5 points for every $1 spent on all other purchases.'),
(2, 'Earn 2x miles at restaurants worldwide'),
(5, 'Earn 5% cash back at supermarkets, drug stores and gas stations (after your first $6,500 annual spend).'),
(3, 'Earn 3X points for every $1 on eligible net travel purchases and mobile wallet spending.'),
(1, 'Earn 1% on all other purchases.'),
(1, 'Earn 1 mile per dollar spent on all purchases.'),
(1, 'Earn 1% cash back on all your purchases. Pay on time to boost your cash back to a total of 1.25% for that month.'),
(2, 'Earn unlimited 2% at grocery stores.'),
(1, '1% Cash Back on all other Purchases.'),
(2, 'Earn even more on tickets purchased from United — get an additional 0.5 mile for a total of 2 miles per $1 spent.'),
(3, '3 Miles on every dollar spent on eligible purchases made directly with Delta'),
(1.5, 'Earn 1.5% in rewards on all purchases and earn a 10% bonus when you redeem your rewards for cash back into an eligible TD Ameritrade account.'),
(2, '2% Cash Back at Restaurants on the first $500 in spend each month.'),
(3, 'Earn 3% cash rewards on cellular, gas and purchases made at office supply stores.'),
(1, 'Earn 1% cash rebate on all other purchases.'),
(3, 'Earn 3 LifeMiles per $1 spent on Avianca purchases'),
(2, '2% cash back on all gas station, grocery store and drugstore purchases.'),
(1, '1X on all other purchases'),
(3, 'Earn 3% cash back on travel.'),
(25, '25 points per $1 spent when you stay at any IHG hotel'),
(10, 'Earn 10 HHonors Bonus Points per $1 spent on hotel stays within the Hilton HHonors portfolio.'),
(3, 'Earn 3 points per dollar spent at supermarkets.'),
(3, 'Earn 3 Points per $1 spent on airline, hotel, taxi (including Uber and Lyft), limousine, rental car, train, bus, restaurant, fast food, and takeout food dining purchases.'),
(3, 'Get 3% Cash Back on gas when you use your PIN at the pump and 1.5% Cash Back at all other gas stations.'),
(2, '2 points per dollar spent on travel'),
(2, 'Earn 2 points (1 point and 1 bonus point) for every $1 in qualifying purchases for the first 12 billing cycles after your account is opened'),
(1, '1 point for every $3 spent outside of Ulta Beauty'),
(1.5, '1.5% per $1 spent'),
(12, '12X points per dollar for purchases made directly with hotels and resorts in the Hilton portfolio'),
(5, '5 points per dollar spent on television'),
(2, 'Earn 2% Cash Back Rewards at the Exchange, MilExch.com, Express Fuel Stations, MWR Merchants and the Commissary.'),
(2, '2x points on dining'),
(5, 'Earn 5 points for every $1 spent on Amazon.com and Whole Foods Market.'),
(2, '2X Points for each dollar of eligible purchases made when you book on the American Express Travel website'),
(1, 'Earn 1 Alaska Airlines mile per dollar spent on all purchases.'),
(5, '5x points for Restaurants'),
(1, 'Earn 1 Chase Ultimate Rewards point per dollar everywhere else.'),
(1, '1X Points on all other purchases'),
(2, 'Earn 2X miles on travel and dining.'),
(2, '2 points per $1 spent on purchases at gas stations, grocery stores, and restaurants.'),
(2, 'Get unlimited 2% cash back on every purchase for your business, with no minimum to redeem.'),
(14, 'EARN 14X HILTON HONORS BONUS POINTS when you make eligible purchases on your Card at participating hotels or resorts within the Hilton Portfolio.'),
(0, 'No bonus earnings.'),
(3, '3x Delta SkyMiles for each dollar spent on qualifying Delta purchases.'),
(2, '2% cash back on groceries.'),
(3, 'Earn 3 points for every dollar spent on travel'),
(0, 'No points earned outside of Best Buy.'),
(1, 'Earn 1% on all other purchases'),
(1, '1% on all other purchases.'),
(1, '1% back on all other purchases.'),
(3, '3X Points per dollar on other purchases'),
(1, 'Servus Circle Rewards (1 point for every $1 spent on eligible purchases)'),
(3, '3 miles per $1 spent directly on Virgin Atlantic purchases'),
(1, 'Earn 1X miles on all other purchases'),
(5, 'Earn 5% back at Home Improvement Store and Popular Streaming Services from 7/1/2020 - 9/30/2020 on up to $1,500 in purchases.'),
(1, 'Earn 1 AAdvantage mile per dollar spent.'),
(2, '2 point per dollar spent on all other purchases'),
(6, '6x points for every $1 spent at over 7,000 participating Marriott BonvoyTM hotels worldwide'),
(1, '1% back in rewards everywhere else'),
(1, 'Earn 1 ABOC Rewards point for every $1 spent.'),
(1, 'Earn 1% Cash Back Rewards on purchases everywhere.'),
(2, 'Get 2% Cash Back on purchases'),
(1.25, 'Earn rebates up to 1.25% on your everyday purchases.'),
(5, '5% back in Uber Cash through Uber Eats, 3% back on restaurant purchases.'),
(3, 'Earn 3 Hilton HHonors Bonus Points for all other eligible purchases on your Card.'),
(1, '1 Bonus Point per $1 spent on purchases anywhere else you use your card. Points don''t expire as long as your World of Hyatt Credit Card account is open.'),
(1, '1X points for each dollar you spend.'),
(5, 'Earn 5X points at the PlayStationTMStore and on purchases of PlayStation and Sony products at authorized retailers with purchase confirmation'),
(2, 'Earn 2 LifeMiles per $1 spent on Avianca purchases'),
(1, '1x Points on all other purchases'),
(5, 'Earn 5 percent on fuel purchases (on first $6,000 per year in purchases, then 1% on purchases after).'),
(1, 'Earn 1x points on other purchases.'),
(2, 'Earn 2% at grocery stores and 1% on all other purchases.'),
(2, '1.5% cash back on purchases; 2% cash back for clients who bank and save with Key.'),
(1.5, 'Earn 1.5 points per dollar on purchases'),
(5, 'Earn 5X miles on hotel and rental car bookings through Capital One Travel℠ using a Spark Miles card.'),
(2, 'Earn 2% cash back on all Apple Pay purchases.'),
(1, '1% back Everywhere else Mastercard® is accepted'),
(1, '1x points on All Other Purchases'),
(2, '2 points per dollar at restaurants and grocery stores'),
(1, '5% cash back on a category of your choice.'),
(2, 'Earn 2 HHonors Bonus Points for each $1 spent on all other purchases.'),
(1, 'Earn one Membership Rewards® point for each dollar you spend on eligible purchases'),
(4, 'Selectable Category'),
(2, 'Selectable Category'),
(1, 'Earn 1 point and 1 tier credit per $1 spent everywhere else'),
(2, '2 points per dollar spent at gas stations'),
(1, 'Get unlimited 1X miles on every purchase for your business.'),
(6, 'Earn 6 points per $1 spent at over 7,000 participating Marriott Bonvoy hotels worldwide'),
(3, '3% back in Uber Cash on hotels, airfare, and restaurant purchases.'),
(0, 'Earn at least 15 POINTS for every $1 you spend on qualifying purchases with your Lane Bryant Credit Card at Lane Bryant, Lane Bryant Outlet and lanebryant.com; Cacique and cacique.com; and Catherines and catherines.com.'),
(2, 'Double FlexPoints for every $1 spent on gas, office supply or airline purchases — whichever you spend most on each monthly billing cycle'),
(2, 'Earn 2 points per $1 spent on travel purchases'),
(2, 'Earn 2 AAdvantage® miles for every $1 spent at gas stations.'),
(4, '4% at L.L.Bean'),
(1.575, '1.5% cash back on all purchases, and gives you a 5% cash rewards bonus toward your next redemption when you cash in.'),
(1, 'Earn 1 mile per $1 on all other purchases'),
(3, '3% back in rewards on dining, grocery and utility purchases'),
(1, 'Earn 1x miles on all other purchases.'),
(2, 'Earn 2% back on eating out and other gas purchases.'),
(5, 'Earn 5X Hilton HHonors Bonus Points for each dollar of eligible purchases on your Card at restaurants, gas stations and supermarkets.'),
(6, '6X Points Per dollar on select travel purchases on car rentals booked directly from select car rental companies'),
(3, 'Earn 3x points on:  Eating out and ordering in;  Gas, rideshares, and transit;  Flights, hotels, homestays, and car rentals;  Popular streaming services'),
(1.25, 'Earn 1.25% cash back  on every purchase'),
(1, '1% cash back rewards on eligible purchases'),
(2, '2X Miles at Restaurants'),
(2, 'Earn 2X miles on eligible purchases made directly from Hawaiian Airlines'),
(1, 'Earn 1X Membership Rewards® points for all other purchases.'),
(1, 'Earn 1 Rewards Point everywhere else American Express is welcomed.'),
(3, 'Earn 3X Membership Rewards® points on flights booked directly with airlines or on amextravel.com.'),
(1, '1% value for cash back redemptions'),
(5, 'Earn 5 points per $1 spent when you stay at our hotels.'),
(3, 'Earn 3X Hilton HHonors Bonus Points for all other eligible purchases on your Card.'),
(1, 'Earn 1 point for every $1 spent on purchases everywhere else Mastercard is accepted.'),
(1, '1 award mile per $1 spent on all other purchases'),
(3, '3X points on travel'),
(5, '5% back Walmart.com & Walmart app, Grocery Pickup and Delivery'),
(2, 'Earn two miles per $1 spent on hotels'),
(1, 'Earn 1X point on all other purchases.'),
(2, '2% at gas stations'),
(0, 'No points earned.'),
(1, '1 miles per dollar spent on all other purchases'),
(20, '20 points per $1 spent on Dining and Travel'),
(2, '2 Miles per dollar spent on purchases at restaurants.'),
(1, '1% unlimited cash back rewards on all other purchases.'),
(3, '3% cash rewards earned for up to $2,500 spent on gas, grocery, and drugstore purchases for the first 6 months.'),
(2, 'Earn 2 points per dollar spent on all other purchases.'),
(3, 'Earn 3X points per $1 spent on travel from flights, cruise lines and hotels to car rentals, trains and taxis (immediately after earning your $300 annual travel credit).'),
(1, '1% Back in Rewards for every $1 spent anywhere else Mastercard is accepted'),
(5, 'Earn 5% back at Restaurants and PayPal from 7/1/2020 - 9/31/2020 on up to $1,500 in purchases.'),
(3, 'Earn 3 reward points on all retail purchases'),
(1, 'Earn 1% cash back on all purchases.'),
(1, 'Earn 1 point for every other $1 spent.'),
(2, 'Earn 2% for gas, groceries and toll'),
(2, '2X points on gas'),
(1, 'Unlimited 1% back on other purchases everywhere Visa is accepted.'),
(2, '2X points on gas and groceries'),
(1, 'Earn 1 point per dollar spent on all other purchases.'),
(1.8, 'Earn an unlimited 1.8% cash back on every purchase.'),
(2, 'Earn 2 Real Life Reward points for every $1 spent on gas and grocery store purchases.'),
(3, '3 Miles on every dollar spent on purchases made directly with hotels'),
(2, '2% Shell rebates on your first $10,000 Dining and Groceries purchases (per year)'),
(1, '1 point for every $1 spent on purchases anywhere else you use your card — there are no limits to the points you can earn.'),
(5, 'Earn 5% rebates on all participating BP location purchases.'),
(2, 'Earn 2 Rewards Points at Dillard''s with a Dillard''s Card – in store, online or via catalog or phone.'),
(0, 'Earn 10% back in Rewards - You''ll receive a $25 Reward Certificate for every $250 you spend OR Choose 12 months special financing on purchases of $750 or more'),
(1, '1 Mile on every eligible dollar spent on purchases.'),
(1, 'Earn unlimited 1% on all other purchases.'),
(3, '3% cash back on restaurants and eligible travel.'),
(2, 'Earn 2x miles for every dollar spent on eligible purchases made directly with Delta.'),
(1.25, 'Earn 1.25% cash back on all purchases'),
(1, 'Earn 1% back on other non-BJ''s purchases everywhere else MasterCard is accepted.'),
(2, '2 Points per $1 spent on eligible Gas and Grocery stores'),
(2, '2X Points for each dollar of eligible purchases made when you book on the American Express Travel website'),
(1, 'Earn 1 Membership Rewards® point for each dollar you spend on eligible purchases.'),
(1, '3% cash back in the category of your choice: gas, online shopping, dining, travel, drug stores, or home improvement/furnishings. 1% cash back on all other purchases'),
(2, '2X points on gas and dining out'),
(2, '2% back in rewards at gas stations & supermarkets'),
(2, 'Earn 2 points for every $1 you spend on social media and search engine advertising, Internet, cable, and phone services.'),
(5, '5X Membership Rewards® points on flights booked directly with airlines or with American Express Travel.'),
(3, 'EARN 3X MARRIOTT BONVOY POINTS at U.S. restaurants and on flights booked directly with airlines.'),
(1, '1% back on all gas purchases.'),
(0, 'Merchant-specific rewards only.'),
(1, 'Earn unlimited 1% cash back on every purchase for your business.'),
(2, '2X Points on new dining purchases'),
(5, '5% cash back at U.S. office supply stores and on wireless telephone services purchased directly from U.S. service providers'),
(2, '2 award miles per $1 spent on ticket purchases from Miles & More integrated airline partners'),
(1.5, '1.5% After 12 on-time monthly payments'),
(1.5, 'Unlimited 1.5% Cash Rewards. No category limitations or quarterly activations.'),
(1, '1% back in rewards on all other purchases'),
(6, '6X Points Per dollar on select travel purchases at U.S. restaurants'),
(1, 'Earn 1% back in reward dollars on every other purchase anywhere Mastercard is accepted'),
(2, 'Earn 2% cash back on dining'),
(2, 'Earn 2% in TravelBank cash per $1 spent on tickets purchased from United.'),
(1, 'Earn 1 TrueBlue point for each $1 spent on other eligible purchases.'),
(5, '5 points per $1 spent in eligible net purchases everywhere else.'),
(2, 'Earn 2% Money-Back Rewards on your everyday purchases in two 2% Money-Back Categories of your choice, and 0.50% Money-Back Rewards on all your other everyday purchases.'),
(2, 'Earn 2 TrueBlue points for each $1 spent on JetBlue flights, gas, car rental, office supplies and equipment, and wireless phone charges.'),
(2, 'Earn 2X back on all purchases.'),
(1, '1% cash back on everything else.'),
(1.5, '1.5% Cash Back on every purchase'),
(1, 'Earn 1% in reward dollars on all other purchases.'),
(1, '1 point per $1 spent on all other purchases'),
(1, 'Earn 1% back on all other purchases.'),
(3, '3 points for flights booked directly with airlines'),
(0, 'No other bonus earnings.'),
(1, '1X on All Other Purchases'),
(1, 'Earn 1X on other purchases.'),
(2, '2% Cash Back on department stores and movie theaters'),
(1, 'Earn one mile for every $1 you spend anywhere else'),
(1, 'Earn 1 point for every $1 you spend on all other purchases.'),
(1, 'Earn 1 mile per dollar spent everywhere else.'),
(2, '3% MCO rewards on all card spending'),
(1, '1% cash back on other purchases'),
(1, '1% rebate on all net purchases applied directly to your mortgage.'),
(2, '2% at restaurants'),
(1, 'With Pro and Teams, 1% Cashback on all your purchases on up to $4,500 spend per month.'),
(2, '2x points per $1 spent on all other purchases'),
(1, '1.5 Miles After you spend $150,000 in purchases on your Card in a calendar year, 1 Mile on every eligible dollar spent on other purchases.'),
(1, '1% in points on all other eligible purchases'),
(1, 'Earn 1 point per $1 spent.'),
(1.5, '1.5 points per dollar spent on all purchases.'),
(3, '3% Cash Back at U.S. supermarkets, up to $6,000 per year in purchases (then 1%).'),
(1, 'Earn 1X miles on all other purchases.'),
(2, 'Earn 2 AAdvantage® miles for every $1 spent at restaurants'),
(1.5, '1.5% cash back on general purchases'),
(5, '5x points for Air Travel'),
(2, 'Earn 2 MileagePlus miles for each $1 spent on local transit and commuting, including train tickets, taxi cabs, mass transit, tolls and ride share services.'),
(1.5, '1.5% value for cash back redemptions'),
(5, 'Earn 5 points for every $1 spent on Fairmont stays.'),
(1, '1% cash back on all other purchases'),
(1, 'Earn 1% cash back on all other purchases.'),
(5, '5% Back or 90 days to pay interest free on U.S. purchases at Amazon Business, AWS, Amazon.com and Whole Foods Market with an eligible Prime membership'),
(3, 'Earn 3 points per $1 at U.S. restaurants, at U.S. office supply stores, and on services from U.S. wireless telephone service providers'),
(4, '4% MCO rewards on all card spending'),
(2, 'Earn two miles per $1 spent on car rentals'),
(1, 'Enjoy 1% cash rewards for other purchases.'),
(1, '1x point per $1 for all other purchases.'),
(1, 'Earn 1% cash back on purchases everywhere.'),
(8, 'You''ll earn 8 points per $1 spent on Virgin America flights'),
(6, 'EARN 6X MARRIOTT BONVOY POINTS on eligible purchases at participating Marriott Bonvoy hotels.'),
(2, 'Earn 2 points for every $1 spent on airline tickets purchased directly with the airlines, at car rental agencies, and on transit and commuting.'),
(3, '3x points for Hotels'),
(5, '5% cash back at all bookstores, including Amazon.com'),
(5, '5 points per dollar spent on restaurants this quarter after activating.'),
(0, 'No bonus points.'),
(2, '2 miles per dollar spent on all other purchases'),
(1, 'Earn 1 TrueBlue point per dollar on net purchases.'),
(2, 'Earn 2 Rapid Rewards points at Southwest Hotel and Car Rental Partners.'),
(1, '1% back everywhere else'),
(2, 'Earn 2X Miles per dollar spent on Delta purchases.'),
(1, 'Earn 1% cash back on all other purchases (after $6,500 annual spend).'),
(1, 'Earn 2 points per $1 spent on all other purchases'),
(5, 'Earn 5% off all Lowe''s purchases.'),
(1, '2% cash back on your choice of one everyday category (like gas, groceries, or restaurants). 1% cash back on everything else.'),
(2, '2X points on the first $50,000 in purchases each year.'),
(6, '6X Marriott Bonvoy points for each dollar of eligible purchases at participating Marriott Bonvoy hotels.'),
(2, '2 Points per $1 on every eligible net purchase, every time.'),
(1.5, 'Earn 1.5% in TravelBank cash per $1 spent on all other purchases.'),
(1, '1x Membership Rewards points on other purchases'),
(3, 'Earn 3% Cash Back on dining'),
(2, '2 Bonus Points per $1 spent at restaurants, on airline tickets purchased directly from the airline, local transit and commuting as well as fitness club and gym memberships.'),
(1, 'Earn 1% Cash Back on all other eligible purchases'),
(2, 'You’ll earn 2X Rewards Program Points on new travel purchases – including airline, hotels, and car rentals'),
(3, '3% in points on eligible purchases at grocery stores & restaurants (on the first $10,000 of combined gas, grocery and restaurant purchases per calendar year and 1% thereafter)'),
(1, 'One FlexPoint for every $1 spent in net purchases.'),
(1, 'Earn 1 point per $1 spent on other purchases'),
(2, 'Get 2% cash back every day, every time you use your card. No exceptions. No rotating categories to keep track of.'),
(2, 'Earn 2 AAdvantage miles for each $1 spent at grocery stores, including grocery delivery services'),
(3, 'Earn 3% Cashback On Dining, Select Entertainment, Online at Marvel.com and Marvel''s Official Merchandise Booths.'),
(1.5, 'Earn unlimited 1.5% cash back on every purchase, every day.'),
(3, '3X Points on travel and dining worldwide'),
(1, '1x points on all other purchases'),
(1, 'Earn 1 ThankYou® Point for every $1 you spend on all other purchases.'),
(3, '3x points for commercial air travel'),
(2, '2 points per dollar spent at US supermarkets'),
(2, 'Earn unlimited 2% rewards on all purchases with $1,000 in monthly direct deposits to a BBVA deposit account (Please note rewards decrease to 1.5% without the monthly direct deposit)'),
(4, '9 Bonus points total for Hyatt stays - 4 Bonus Points per $1 spent at Hyatt hotels & 5 Base Points per $1 you can earn as a World of Hyatt member'),
(5, '5% off everyday at Target and Target.com'),
(3, 'Earn 3 Alaska Airlines miles per dollar spent on Alaska Airlines tickets/vacation packages/cargo purchases.'),
(1, '1 Point per $1 spent everywhere else Mastercard is accepted'),
(3, 'Earn 3 points per dollar spent on all qualifying AAA and travel purchases.'),
(1, 'Earn one ScoreCard point for every dollar you spend with the card'),
(3, '3x Membership Rewards points at restaurants worldwide'),
(1, '1 point per dollar on all other purchases'),
(4, '4% back on dining. Restaurants, takeout, and bars, including UberEATS.'),
(2, '2% cash back rewards on gas and at grocery and drug stores (up to $1,500 spend per quarter in these combined purchase categories).'),
(1, 'Earn 1 point per dollar spent.'),
(2, '2x points per $1 spent on all other purchases.'),
(1, 'Earn 1X point for every $1 spent on any other category (3X points with your Mobile Wallet)'),
(2, 'Earn 2x points per $1 spent on all other purchases.'),
(1, 'Earn 1X AAdvantage® miles  for every one dollar spent on all other purchases'),
(0, 'No rewards outside of Avenue purchases.'),
(12, 'Earn 12 Hilton HHonors Bonus Points for each dollar of eligible purchases charged on your Card directly with a participating hotel or resort within the Hilton Portfolio.'),
(5, 'Earn 5 points for every $1 spent at over 4,000 Marriott locations worldwide, including our exclusive luxury hotel partner, The Ritz-Carlton®.'),
(4, 'Earn 4X Membership Rewards® points at US supermarkets, on up to $25,000 per year in purchases, then 1X.'),
(1.5, '1.5% Cash Back on your purchases.'),
(2.5, '2.5% cash back on all your purchases'),
(1, '5% cash back on your first $2,000 in combined net purchases each quarter on two categories you choose. 1% cash back on everything else.'),
(2, '2 points per dollar spent on restaurants'),
(1, 'Earn up to 1% cashback in any currency, including cryptocurrencies (earn 0.1% in Europe and 1.0% outside of Europe on your card payments in any of our supported currencies, including Bitcoin, Litecoin, and Ether)')